version: 2

sources:
  - name: ghcn_d
    database: bigquery-public-data
    schema: ghcn_d
    tables:
      - name: ghcnd_2020
      - name: ghcnd_2019
      - name: ghcnd_2018
      - name: ghcnd_2017
      - name: ghcnd_2016
      - name: ghcnd_2015
      - name: ghcnd_2014
      - name: ghcnd_2013
      - name: ghcnd_2012
      - name: ghcnd_2011
      - name: ghcnd_2010
      - name: ghcnd_2009
      - name: ghcnd_2008
      - name: ghcnd_2007
      - name: ghcnd_2006
      - name: ghcnd_2005
      - name: ghcnd_2004
      - name: ghcnd_2003
      - name: ghcnd_2002
      - name: ghcnd_2001
      - name: ghcnd_2000
      - name: ghcnd_1999
      - name: ghcnd_1998
      - name: ghcnd_1997
      - name: ghcnd_1996
      - name: ghcnd_1995
      - name: ghcnd_1994
      - name: ghcnd_1993
      - name: ghcnd_1992
      - name: ghcnd_1991
      - name: ghcnd_1990
      - name: ghcnd_1989
      - name: ghcnd_1988
      - name: ghcnd_1987
      - name: ghcnd_1986
      - name: ghcnd_1985
      - name: ghcnd_1984
      - name: ghcnd_1983
      - name: ghcnd_1982
      - name: ghcnd_1981
      - name: ghcnd_1980
      - name: ghcnd_1979
      - name: ghcnd_1978
      - name: ghcnd_1977
      - name: ghcnd_1976
      - name: ghcnd_1975
      - name: ghcnd_1974
      - name: ghcnd_1973
      - name: ghcnd_1972
      - name: ghcnd_1971
      - name: ghcnd_1970
      - name: ghcnd_1969
      - name: ghcnd_1968
      - name: ghcnd_1967
      - name: ghcnd_1966
      - name: ghcnd_1965
      - name: ghcnd_1964
      - name: ghcnd_1963
      - name: ghcnd_1962
      - name: ghcnd_1961
      - name: ghcnd_1960
      - name: ghcnd_1959
      - name: ghcnd_1958
      - name: ghcnd_1957
      - name: ghcnd_1956
      - name: ghcnd_1955
      - name: ghcnd_1954
      - name: ghcnd_1953
      - name: ghcnd_1952
      - name: ghcnd_1951
      - name: ghcnd_1950
      - name: ghcnd_stations
